version: '3.8'

services:
  mysql:
    image: mysql:lates
    container_name: mysql-heart
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: Di@rreiaMortal
      - MYSQL_DATABASE: heart

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: